### ISSUE TITLE
Add a license file?

### ISSUE THREAD

**Issue by RobAley** [MarQ-ZA/footnotes-traditional#1]
Hi Marc,

This is quite a useful plugin, thanks for writing/publishing it. Are you willing to add a license[1] (e.g. MIT, Apache, LGPL etc.) to the repo so that it can be used e.g. in other opensource projects?

Many thanks

[1] [Github license docs](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)

**Comment by marc-pelteret** [comment]
Hi Rob,

Glad to hear you find it useful. Thanks for raising the issue of the licence. I've added one.

Marc

**Comment by RobAley** [comment]
That's great, many thanks.
